name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    # branches: [ "main" ]
    # Publish semver tags as releases.
    tags:
      - 'v*'
    paths:
      - 'api/**'
      - 'rproxy/**'
      - 'scan_domain/**'
      - 'scan_tls/**'
  # pull_request:
  #   branches: [ "main" ]

env:
  REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        include:
          - image: ghcr.io/ciso360ai/api
            dockerfile: api/Dockerfile
            context: api/.
          - image: ghcr.io/ciso360ai/rproxy
            dockerfile: rproxy/Dockerfile
            context: rproxy/.
          - image: ghcr.io/ciso360ai/scan_domain
            dockerfile: scan_domain/Dockerfile
            context: scan_domain/.
          - image: ghcr.io/ciso360ai/scan_tls
            dockerfile: scan_tls/Dockerfile
            context: scan_tls/.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3.1.0

      - name: Log to registry ${{ env.REGISTRY }}
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          # images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          images: ${{ matrix.image }}
          tags: |
              type=semver,pattern={{version}}
              type=schedule,pattern={{date 'YYYYMMDD'}}
              type=raw,value=latest

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@af5a7ed5ba88268d5278f7203fb52cd833f66d6e # v5.2.0
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
